node:
    env_file:
        - docker.env      # edit first :D
    build: node
    container_name: "hex_node"
    volumes:
        - "../www:/home/node/www"
        - "./:/home/node/docker"
    ports:
        - "3000:3000"
        - "8080:8080"
        - "8443:443"
        - "9080:9080"

logio_harvester:
    image: temal/logio-harvester
    container_name: "hex_logio_harvester"
    links:
        - logio_server
    volumes:
        - "./logio/:/home/logio/.log.io"
        - "./data/log:/home/logio/log"

logio_server:
    image: temal/logio-server
    container_name: "hex_logio_server"
    ports:
        - 28777:28777
        - 28778:28778
